# Generated by Django 4.2.9 on 2026-03-24 19:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sleeplog',
            name='calories_yesterday',
        ),
        migrations.RemoveField(
            model_name='sleeplog',
            name='sleep_hours',
        ),
        migrations.RemoveField(
            model_name='sleeplog',
            name='sleep_quality',
        ),
        migrations.RemoveField(
            model_name='sleeplog',
            name='steps_yesterday',
        ),
        migrations.RemoveField(
            model_name='sleeplog',
            name='stress',
        ),
        migrations.AddField(
            model_name='sleeplog',
            name='deep_sleep',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='sleeplog',
            name='light_sleep',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='sleeplog',
            name='rem_sleep',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='sleeplog',
            name='respiratory_rate',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)]),
        ),
        migrations.AlterField(
            model_name='sleeplog',
            name='hrv',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='sleeplog',
            name='resting_hr',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(220)]),
        ),
    ]
